### PR TITLE
Development

### LINKED ISSUE #247: [Blockly][Codegenerator] | WiFi - WPA2 Enterprise Block
### Block description
senseBox MCU-S2 can now connect to WPA2 Enterprise networks (e.g. eduroam)  

### Expected block behaviour 
Add new block which allows to add the network name, user credentials

### LINKED ISSUE #248: [Blockly][UI] Add feature to check the board type when loading a programmcode
**Is your feature request related to a problem? Please describe.**
As we have now different boards using different architectures (SAMD and ESP32) there should be a check for which the code was created. There might be features which are unique to specific boards

**Describe the solution you'd like**
We could extend the xml with a board tag.

**Describe alternatives you've considered**
It might be useful to switch to the json serialization scheme which was introduced in blockly lately. Migration guide is public https://docs.google.com/document/d/1wv5ORrO4icVHeU15FLSn37mdNLyJpQbMTo7mmTqsGl0/edit?hl=de

### LINKED ISSUE #249: Code Editor still uses fixed compiler URL
The Code Editor still makes use of the fixed compiler URL

### LINKED ISSUE #254: [Blockly][Codegenerator] Add LED Matrix
Add Block and Code for the new LED Matrix.

For the block we might use https://github.com/google/blockly-samples/tree/master/plugins/field-bitmap for the block

For the Arduino Code we need to check libraries might use: https://github.com/adafruit/Adafruit_NeoMatrix

### LINKED ISSUE #255: [Blockly][Codegenerator] Allow openSenseMap Block without Interval Block around
### Block description
Currently the openSenseMap Block needs to be nested inside the interval block. When using other structures such as the case structure the interval block is not needed

### LINKED ISSUE #258: [Blockly][Codegenerator] Adjust SD-Card when MCU-S2 is selected
Needs to be adjusted to [this example](https://github.com/sensebox/senseBox-MCU-S2-ESP32S2/blob/main/examples/sd-card/sd-card.ino). The code in blockly somehow breaks the MCU where you have to manually reset it
  -  addMeasurement' was not declared in this scope When using "Save Measurement" Block

### LINKED ISSUE #259: [Blockly][Codegenerator] Change WiFi when MCU-S2 is selected
Getting error message when trying to use the WiFi Block

### LINKED ISSUE #275: [Blockly][Codegenerator] Add ESP Now
ESP now is a nice feature to communicate directly between two or more devices. 

- [ ] create new Category
- [ ] create sender sketch
- [ ] create receiver sketch

### LINKED ISSUE #281: [Blockly][Codegenerator] Phyphox Blocks
### Block description
Currently there is no max length for the unit and the label. The library only allows 5 characters for the unit and 20 for the label.

### PR DESCRIPTION
**Pull request by mariopesch**
This PR 
closes #255 
closes #258 
closes #249 
closes #259 
closes #273 
closes #281 
closes #254 
closes #247 
closes #275
closes #248

### CODE REVIEW

**Comment by Thiemann96** [comment]
closes #249 
closes #259

**Comment by mariopesch** [comment]
closes #281

**Comment by mariopesch** [comment]
closes #254

**Comment by Thiemann96** [comment]
closes #251

**Comment by Thiemann96** [comment]
- closes #257 
 - closes #248

**Comment by mariopesch** [comment]
@PaulaScharf regarding #296 can you add some padding so the text does not stretch so much?
image

**Pull request merged**
