### PR TITLE
Add ESP-Now

### PR DESCRIPTION
**Pull request by PaulaScharf**
Implementation of #275 

Ready to be tested :)

### CODE REVIEW

**Comment by mariopesch** [comment]
@PaulaScharf successfully tested to send a string from one mcu-s2 to another. Do you think we can easily implement sending a measurement value e.g. from a temperature sensor?

**Review by mariopesch — APPROVED** [review]
LGTM!

**Comment by PaulaScharf** [comment]
> @PaulaScharf successfully tested to send a string from one mcu-s2 to another. Do you think we can easily implement sending a measurement value e.g. from a temperature sensor?

works now

**Comment by mariopesch** [comment]
@PaulaScharf fantastic!! Tested with temperature sensor and it works!

**Comment by mariopesch** [comment]
I'll merge to development

**Pull request merged**
